Slight modification to generate based on environment...

diff --git a/colorizer b/colorizer
--- a/colorizer
+++ b/colorizer
@@ -1,10 +1,32 @@
 #!/bin/bash
 
 dir=~/.themes/colorizer/
+gtk3_settings=~/.config/gtk-3.0/settings.ini
+gtk2_settings=~/.gtkrc-2.0
 pwd=/usr/bin/pwd
 xfwm="one_new"
 gtk="fantome"
 
+has_xfce=0
+has_gtk2=0
+has_gtk3=0
+
+# Check if XFCE is an option
+if ! [ -x "$(command -v xfconf)" ]; then
+	has_xfce=1
+fi
+
+# Check if GTK2 is an option
+if [ -f "$gtk3_settings" ]; then
+	has_gtk3=1
+fi
+
+# Check if GTK3 is an option
+if [ -f "$gtk3_settings" ]; then
+	has_gtk3=1
+fi
+
+# Grabs colors from Xresources
 fill_color() {
 	get_color() {
 		xrdb -query | grep "^*$1" -m 1 | cut -f 2 | cut -d'#' -f 2
@@ -13,6 +35,7 @@ fill_color() {
 	get_colors_bg=$(get_color "background")
 }
 
+# Creates the XFWM theme
 xfwm_themer() {
 	if [ ! -d "$dir"xfwm4/ ]; then
 		mkdir -p "$dir"xfwm4/
@@ -20,6 +43,7 @@ xfwm_themer() {
 		rm "$dir"xfwm4/*
 	fi
 
+	# Replace the values in the copied theme
 	cp "$($pwd)"/xfwm4/"$1"/* "$dir"xfwm4/
 	sed -i s/"color_bg"/"${get_colors_bg}"/g "$dir"xfwm4/*
 	sed -i s/"color_1"/"$(get_color "color1")"/g "$dir"xfwm4/*
@@ -31,10 +55,12 @@ xfwm_themer() {
 	sed -i s/"color_7"/"$(get_color "color7")"/g "$dir"xfwm4/*
 }
 
+# Creates the GTK themes
 gtk_themer() {
 	rm -rf "$dir"gtk-*
 	cp -r "$($pwd)"/gtk/"$1"/* "$dir"
 
+	# Replace the values in the copied theme
 	find "$dir"gtk-2.0/ -type f -exec sed -i s/"color_bg"/"${get_colors_bg}"/g {} \;
 	find "$dir"gtk-2.0/ -type f -exec sed -i s/"color_2"/"$(get_color "color2")"/g {} \;
 	find "$dir"gtk-2.0/ -type f -exec sed -i s/"color_1"/"$(get_color "color1")"/g {} \;
@@ -47,24 +73,73 @@ gtk_themer() {
 	find "$dir"gtk-3.0/ -type f -exec sed -i s/"color_7"/"$(get_color "color7")"/g {} \;
 }
 
+# Applies the theme
 apply_theme() {
-	xfconf-query -c xfwm4 -p /general/theme -s "adwaita"
-	xfconf-query -c xfwm4 -p /general/theme -s "colorizer"
-	xfconf-query -c xsettings -p /Net/ThemeName -s "adwaita"
-	xfconf-query -c xsettings -p /Net/ThemeName -s "colorizer"
+	# Only apply to XFCE if we can
+	if [ "$has_xfce" ]; then
+		xfconf-query -c xfwm4 -p /general/theme -s "adwaita"
+		xfconf-query -c xfwm4 -p /general/theme -s "colorizer"
+		xfconf-query -c xsettings -p /Net/ThemeName -s "adwaita"
+		xfconf-query -c xsettings -p /Net/ThemeName -s "colorizer"
+
+		echo ">> Applied: XFWM theme"
+	else
+		echo ">> Skipping Apply: XFWM theme, \"xfconf-query\" missing"
+	fi
+
+	# Only apply to GTK3 if we can
+	if [ "$has_gtk3" ]; then
+		sed -i "/gtk-theme-name=.*/d" "$gtk3_settings"
+		echo "gtk-theme-name=colorizer" >> "$gtk3_settings"
+
+		echo ">> Applied: GTK3 theme"
+	else
+		echo ">> Skipping Apply: GTK3, \"${gtk3_settings}\" missing"
+	fi
+
+	# Only apply to GTK2 if we can
+	if [ "$has_gtk2" ]; then
+		sed -i "/gtk-theme-name=.*/d" "$gtk2_settings"
+		echo "gtk-theme-name=colorizer" >> "$gtk2_settings"
+
+		echo ">> Applied: GTK2 theme"
+	else
+		echo ">> Skipping Apply: GTK2, \"${gtk2_settings}\" missing"
+	fi
 }
 
+# Setup
+echo "Generating themes..."
 mkdir -p ~/.themes/colorizer
 fill_color
 
-echo "Generating XFWM4 theme"
-xfwm_themer $xfwm
+# Generate XFCE
+if [ "$has_xfce" ]; then
+	echo ">> Generating: XFWM4 theme"
+	xfwm_themer $xfwm
+else
+	echo ">> Skipping Generation: XFWM4 theme"
+fi
 
-echo "Generating gtk theme"
-gtk_themer $gtk
-cd "$dir"gtk-2.0/ || exit 1
-"$dir"gtk-2.0/render-assets.sh
-cd "$dir"gtk-3.0/ || exit 1
-"$dir"gtk-3.0/render-assets.sh
+# Generate GTK2
+if [ "$has_gtk2" ]; then
+	echo ">> Generating: GTK2 theme"
+	gtk_themer $gtk
+	cd "$dir"gtk-2.0/ || exit 1
+	"$dir"gtk-2.0/render-assets.sh
+else
+	echo ">> Skipping Generation: GTK2 theme"
+fi
 
+# Generate GTK3
+if [ "$has_gtk3" ]; then
+	echo ">> Generating: GTK3 theme"
+	cd "$dir"gtk-3.0/ || exit 1
+	"$dir"gtk-3.0/render-assets.sh
+else
+	echo ">> Skipping Generation: GTK3 theme"
+fi
+
+# Apply the themes to XFWM, GTK2, and GTK3
+echo ">> Applying themes..."
 apply_theme
